### ISSUE TITLE
Read caching on current data and history

### ISSUE THREAD

**Issue by karashiiro** [Universalis-FFXIV/Universalis#552]
There are currently brief periods in which there are no work pool threads available to handle database requests, which cause largely unknown issues including API downtime. I'm currently implementing a read/write cache to alleviate this issue. Ideally, this would be implemented as close to the database as possible, but there are some dirty data types in the database models that can't be reliably serialized by JSON.NET (which I'm using as a bodge copy tool since BinarySerializer is deprecated).

Instead, I believe that API views (to borrow MVC terminology) should be cached and returned on API requests. This makes write-through caching more difficult.

I have currently implemented a read-through cache for single (item, world) requests, with a cache purge in the upload handler. If it works without problems, I will modify the endpoints to use the cache for multi-world and multi-item requests.

**Comment by karashiiro** [comment]
Single item+world requests seem to not be returning incorrect or out of date data, but I want to finish #553 before continuing this so that I can compare the rate of cache hits before and after making further changes.

**Comment by karashiiro** [comment]
Speak of the devil - there's a bug somewhere in here in which an NRE can occur: https://github.com/Universalis-FFXIV/Universalis/blob/b7886b4c0d43f9443d4f7a4bb5bbc86cfbd52edf/src/Universalis.Application/Caching/MemoryCache.cs#L66-L89

Exception text:
```
universalis_1  |       System.NullReferenceException: Object reference not set to an instance of an object.
universalis_1  |          at Universalis.Application.Caching.MemoryCache`2.Get(TKey key) in /source/src/Universalis.Application/Caching/MemoryCache.cs:line 89
universalis_1  |          at Universalis.Application.Controllers.CurrentlyShownControllerBase.GetCurrentlyShownView(WorldDc worldDc, UInt32[] worldIds, UInt32 itemId, Int32 nListings, Int32 nEntries, Boolean noGst, Nullable`1 onlyHq, Int64 statsWithin, Int64 entriesWithin, CancellationToken cancellationToken) in /source/src/Universalis.Application/Controllers/CurrentlyShownControllerBase.cs:line 158
universalis_1  |          at Universalis.Application.Controllers.V1.CurrentlyShownController.Get(String itemIds, String worldOrDc, String listingsToReturn, String entriesToReturn, String noGst, String hq, String statsWithin, String entriesWithin, CancellationToken cancellationToken) in /source/src/Universalis.Application/Controllers/V1/CurrentlyShownController.cs:line 137
universalis_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
universalis_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
universalis_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
universalis_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
universalis_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
universalis_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
```

The line number points to an end-bracket, so I'm going to need to do some manual testing for this.

**Comment by karashiiro** [comment]
I think I'll just remove the read-write lock here and use a simple lock for everything, since I'm running a second-chance cache eviction algorithm, which implies modifying data on reads. If this causes problems, I can use a read-write lock and instead implement an LRU cache.

**Comment by karashiiro** [comment]
Probably fixed caching with https://github.com/Universalis-FFXIV/Universalis/commit/fa66296d955bea7faf4a208cac3ab4d8f279c13c
